### ISSUE TITLE
Respring changes don’t work

### ISSUE THREAD

**Issue by SidekickSparky** [Nosskirneh/SpringArtwork-Public#5]
When making changes to LS/Homescreen it doesn’t respring when I click yes respring and I’m forced to hard reset and rejailbreak every time unable to make changes successfully. 

iPhone 11, iOS 13

253-414-3269 for faster responses thanks.

**Comment by Nosskirneh** [comment]
Are you possibly using Gump?

**Comment by SidekickSparky** [comment]
Yes I am.

**Comment by Nosskirneh** [comment]
Gump is causing this. My tweaks respring using a more lightweight way to avoid erasing battery usage info that otherwise is erased if running `killall SpringBoard`. Gump causes the device to freeze when respringing this way. You can see that for yourself by changing the system language (same respring approach).

I don’t advice anyone to use Gump because of the way it is implemented. I have explained my reasoning [here](https://reddit.com/r/jailbreak/comments/fxwfvi/releasebeta_roadrunner_ios_13_keep_now_playing/).

You can try to contact Gump’s developer, but you will probably not receive any reply as he has been absent since February.

The solution to this issue is to respring elsewhere (in a way that removes battery usage info) or remove Gump.

**Comment by SidekickSparky** [comment]
Okay great. Will remove Gump.

Thanks.
